[Base]
main                    = 000000
main-elevated           = 000000
card                    = 000000

sidebar                 = 000000 
sidebar-alt             = 000000 

text                    = 0cf155
subtext                 = FFFFFF

button-active           = 0cf155
button                  = 053B16
button-disabled         = 000000

highlight               = 09752C
highlight-elevated      = 053B16 

shadow                  = 000000
selected-row            = FFFFFF
misc                    = 7F7F7F
notification-error      = E22134 
notification            = 0cf155
tab-active              = 333333
player                  = 181818

; [WritingDesk]
; ; Theme colours, base is the writing desk.
; main                    = 985a20 
; main-elevated           = 985a20
; card                    = 985a20

; sidebar                 = 985a20 
; sidebar-alt             = 000000 

; text                    = 000000
; subtext                 = FFFFFF

; button-active           = 000000
; button                  = FFFFFF
; button-disabled         = FFFFFF

; highlight               = FFFFFF
; highlight-elevated      = FFFFFF 

; shadow                  = 000000
; selected-row            = FFFFFF
; misc                    = FFFFFF
; notification-error      = FFFFFF 
; notification            = FFFFFF
; tab-active              = FFFFFF
; player                  = FFFFFF

; [BitterSkies]
; main                    = 1d1c21
; main-elevated           = 985a20
; card                    = 985a20

; sidebar                 = 142b44 
; sidebar-alt             = 000000 

; text                    = FFFFFF
; subtext                 = ADB5BD

; button-active           = FFF3C4
; button                  = FFF3C4
; button-disabled         = 000000

; highlight               = 191919
; highlight-elevated      = 152238 

; shadow                  = 000000
; selected-row            = FFFFFF
; misc                    = 7F7F7F
; notification-error      = E22134 
; notification            = 4687d6
; tab-active              = 333333
; player                  = 181818

; [Enchantment]
; main                    = 5f5f66
; main-elevated           = 985a20
; card                    = 985a20

; sidebar                 = 142b44 
; sidebar-alt             = 000000 

; text                    = 3e3135
; subtext                 = ADB5BD

; button-active           = FFF3C4
; button                  = FFF3C4
; button-disabled         = 000000

; highlight               = 191919
; highlight-elevated      = 152238 

; shadow                  = 000000
; selected-row            = FFFFFF
; misc                    = 7F7F7F
; notification-error      = E22134 
; notification            = 4687d6
; tab-active              = 333333
; player                  = 181818

; [GentleBlues]
; main                    = a8bacc
; main-elevated           = 985a20
; card                    = 985a20

; sidebar                 = 142b44 
; sidebar-alt             = 000000 

; text                    = 2d3f56
; subtext                 = ADB5BD

; button-active           = FFF3C4
; button                  = FFF3C4
; button-disabled         = 000000

; highlight               = 191919
; highlight-elevated      = 152238 

; shadow                  = 000000
; selected-row            = FFFFFF
; misc                    = 7F7F7F
; notification-error      = E22134 
; notification            = 4687d6
; tab-active              = 333333
; player                  = 181818

; [SpaceDreams]
; main                    = 000000
; main-elevated           = 985a20
; card                    = 985a20

; sidebar                 = 142b44 
; sidebar-alt             = 000000 

; text                    = 000000
; subtext                 = ADB5BD

; button-active           = FFF3C4
; button                  = FFF3C4
; button-disabled         = 000000

; highlight               = 191919
; highlight-elevated      = 152238 

; shadow                  = 000000
; selected-row            = FFFFFF
; misc                    = 7F7F7F
; notification-error      = E22134 
; notification            = 4687d6
; tab-active              = 333333
; player                  = 181818

; [SpyGames]
; main                    = 99aab8
; main-elevated           = 985a20
; card                    = 985a20

; sidebar                 = 142b44 
; sidebar-alt             = 000000 

; text                    = 000000
; subtext                 = ADB5BD

; button-active           = FFF3C4
; button                  = FFF3C4
; button-disabled         = 000000

; highlight               = 191919
; highlight-elevated      = 152238 

; shadow                  = 000000
; selected-row            = FFFFFF
; misc                    = 7F7F7F
; notification-error      = E22134 
; notification            = 4687d6
; tab-active              = 333333
; player                  = 181818

; [Tranquility]
; main                    = d2dadd
; main-elevated           = 985a20
; card                    = 985a20

; sidebar                 = 142b44 
; sidebar-alt             = 000000 

; text                    = 000000
; subtext                 = ADB5BD

; button-active           = FFF3C4
; button                  = FFF3C4
; button-disabled         = 000000

; highlight               = 191919
; highlight-elevated      = 152238 

; shadow                  = 000000
; selected-row            = FFFFFF
; misc                    = 7F7F7F
; notification-error      = E22134 
; notification            = 4687d6
; tab-active              = 333333
; player                  = 181818